export const types = {
  FETCH_DATA: 'FETCH_DATA',
  GET_USER: 'GET_USER',
  FETCH_TEAM_DATA: 'FETCH_TEAM_DATA',
  FETCH_CRIME_DATA: 'FETCH_CRIME_DATA',
  FETCH_POSITION_DATA: 'FETCH_POSITION_DATA',
}
