export default DropDownArray = [
  // {id: '', name: 'All Teams'},
  {id: 'ari', name: 'Arizona Cardinals'},
  {id: 'atl', name: 'Atlanta Falcons'},
  {id: 'bal', name: 'Baltimore Ravens'},
  {id: 'buf', name: 'Buffalo Bills'},
  {id: 'car', name: 'Carolina Panthers'},
  {id: 'chi', name: 'Chicago Bears'},
  {id: 'cle', name: 'Cleveland Browns'},
  {id: 'cin', name: 'Cincinatti Bengals'},
  {id: 'dal', name: 'Dallas Cowboys'},
  {id: 'den', name: 'Denver Broncos'},
  {id: 'det', name: 'Detroit Lions'},
  {id: 'gb', name: 'Green Bay Packers'},
  {id: 'hou', name: 'Houston Texans'},
  {id: 'ind', name: 'Indianapolis Colts'},
  {id: 'jac', name: 'Jacksonville Jaguars'},
  {id: 'kc', name: 'Kansas City Chiefs'},
  {id: 'la', name: 'Los Angeles Rams'},
  {id: 'mia', name: 'Miami Dolphins'},
  {id: 'min', name: 'Minnesota Vikings'},
  {id: 'ne', name: 'New England Patriots'},
  {id: 'no', name: 'New Orleans Saints'},
  {id: 'nyg', name: 'New York Giants'},
  {id: 'nyj', name: 'New York Jets'},
  {id: 'oak', name: 'Oakland Raiders'},
  {id: 'phi', name: 'Philadelphia Eagles'},
  {id: 'pit', name: 'Pittsburgh Steelers'},
  {id: 'sd', name: 'San Diego Chargers'},
  {id: 'sf', name: 'San Fransisco 49ers'},
  {id: 'sea', name: 'Seattle Seahawks'},
  {id: 'tb', name: 'Tampa Bay Buccaneers'},
  {id: 'ten', name: 'Tennessee Titans'},
  {id: 'was', name: 'Washington Redskins'},
]
